### ISSUE TITLE
Tesco Developer Contribution

### ISSUE THREAD

**Issue by githubteacher** [githubschool/tesco-tuesday-morning-training#1]
# Contribution TODOs

- [x] add new issue for developers to comment on
- [ ] wait for comments to be added
- [ ] add contributors
- [x] use loads of emojis :koala: :snake: :tiger:

**Comment by robathija** [comment]
Hello World!

**Comment by kavitha23** [comment]
Great start of the day

**Comment by tdprasanth** [comment]
I am in!!!

**Comment by afras09** [comment]
Hi !

**Comment by saeedshahab** [comment]
Hello all :smile:

**Comment by rbadolia** [comment]
Hey I am here....

**Comment by ShauryaNigam** [comment]
Greetings!

**Comment by SrinivasRacharla** [comment]
Morning!!

**Comment by vijay1559** [comment]
NIce

**Comment by vaarenyam** [comment]
Commenting on Issues !

**Comment by jshrk** [comment]
Goo GitHub @ Tesco :octocat: :ship:

**Comment by kartikmathpal** [comment]
Hey Buddy !

**Comment by savithaanand** [comment]
HI

**Comment by Raghavan04** [comment]
This is Raghavan from tesco

**Comment by sudhirsinha-github** [comment]
Cool!!

**Comment by SENTHILKG** [comment]
:dancer: 
:dancer: 
:100:

**Comment by Hitesh1912** [comment]
#GITHUB @tesco **best practices **!!**** :) :100:  :dancers:

**Comment by guptashashank** [comment]
HI all,
great start to the morning :)

**Comment by SENTHILKG** [comment]
**trying Markdown**

**Comment by narendramannam** [comment]
:)

**Comment by SrinivasRacharla** [comment]
:santa:

**Comment by srikanthjrao** [comment]
hello :8ball:

**Comment by sindhu-ramki30** [comment]
Interesting start

**Comment by Meenaytesco** [comment]
Very good session ..

**Comment by tdprasanth** [comment]
:100:

**Comment by ThejaswiniG** [comment]
Hii

**Comment by Santhosh-mvit** [comment]
Hey... :)

**Comment by harsh2015** [comment]
Hello All.. :koala:

**Comment by parthy82** [comment]
Hello All

**Comment by kartikmathpal** [comment]
![alt tag](https://assets-cdn.github.com/images/modules/open_graph/github-mark.png)

**Comment by nishant786** [comment]
Hola amigos .....

**Comment by narendramannam** [comment]
emoji: :smile: @githubteacher

**Comment by rbadolia** [comment]
# #hello

**Comment by PavanDKumar** [comment]
Hi All,

Pavan from Tesco :)

**Comment by shawkartick** [comment]
hello github

**Comment by wc92** [comment]
hello github

**Comment by gganjitesco** [comment]
#Github rocks

**Comment by somadattamallick** [comment]
Github@Tesco HSC

**Comment by rbadolia** [comment]
while(alive)
{
Eat();
Sleep();
Code();
Checkin();
}

**Comment by hemanthpoornachandra** [comment]
Lost

**Comment by rajveerabhishek8** [comment]
#justgitIT

**Comment by prafulravindra** [comment]
`
#include<iostream>
	using namespace std;

	int main()
	{
		cout << "Hello World!";
		return 0;
	}
`

**Comment by maniraaa4** [comment]
Hi Github!!!

**Comment by Raghav22900257** [comment]
Hi Git!!!

**Comment by NeelimaH** [comment]
hi

**Comment by sibonayak** [comment]
hi

**Comment by KrithikaRai** [comment]
hi github!

**Comment by b2s2** [comment]
Edit

**Comment by Tejareddy29792** [comment]
Interesting session...

**Comment by PrateekshaGunga** [comment]
Its Good..

**Comment by cksdm008** [comment]
hello!

**Comment by Mounica-s** [comment]
Nice to have github session

**Comment by Rajasekharch** [comment]
Hey...Github!!

**Comment by avbsandhya** [comment]
Hello!!

**Comment by kartikmathpal** [comment]
Hi

**Comment by Shkrsumana** [comment]
hello

**Comment by sauravmawandia** [comment]
:+1: Advanced Session

**Comment by savithaanand** [comment]
hi

**Comment by Kumar-saurabh11** [comment]
sup

**Comment by Santhosh-mvit** [comment]
Second Session started

**Comment by githubteacher** [comment]
:tada: @Kumar-saurabh11 is now a repository collaborator. :balloon:

**Comment by Quininin** [comment]
Great One :+1:

**Comment by githubteacher** [comment]
:tada: @Quininin is now a repository collaborator. :balloon:
